### ISSUE TITLE
Prometheus endpoint

### ISSUE THREAD

**Issue by trajano** [caronc/apprise-api#143]
:bulb: **The Idea**
Provide a /metrics endpoint so we can see the usage in Grafana

:hammer: **Breaking Feature**

**Comment by instantdreams** [comment]
Recommended apprise-api configuration:

1. Add environment variable:

```
ENABLE_PROMETHEUS_METRICS=true
```


2. Restart apprise-api container:

```
cd [directory of apprise-api compose configuration]
docker compose pull;docker compose down;sleep 4;docker compose up --detach
```


3. Confirm that metrics are available

       http://[container-ip]:[container-port]/metrics


4. Add scraper to prometheus configuration:

```
  - job_name: 'apprise'
    static_configs:
    - targets: [ '[container-ip]:[container-port]' ]
      labels:
        host: '[hostname]'
        machine: '[machine-name]'
```


5. Restart prometheus container:

```
cd [directory of prometheus compose configuration]
docker compose pull;docker compose down;sleep 4;docker compose up --detach
```


6. Check target health:

       http://[container-ip]:[container-port]/targets


7. Develop a Grafana dashboard ;)
