### ISSUE TITLE
django.request: Failed Dependency Explanation

### ISSUE THREAD

**Issue by datenzar** [caronc/apprise-api#158]
:mega: **Notification Service(s) Impacted**
Pushover (maybe others)

:lady_beetle: **Describe the bug**
When I create a simple configuration (using Pushover) and then try to send a notification from another machine via curl, I don't receive the notification.

If I call the the scheme directly (without configuration), it works as supposed.

:bulb: **Screenshots and Logs**

On the client side:
```
[INFO] apprise: Loaded 1 entries from memory://
```

On the service side:
```
apprise  | 2023-12-25 04:46:50,101 [INFO] apprise: Loaded 1 entries from memory://
apprise  | 2023-12-25 04:46:50,102 [WARNING] django.request: Failed Dependency: /notify/test
apprise  | 172.18.0.10 - - [25/Dec/2023:11:46:50 +0100] "POST /notify/test HTTP/1.1" 424 72 "-" "curl/7.74.0"
```

:computer: **Your System Details:**
 - OS: Debian with docker 24.0.7 and docker-compose 2.21.0
 - `caronc/apprise:latest` Docker image

:crystal_ball: **Additional context**

Not sure if it's related to caronc/apprise#995 but as I don't get the ' new thread' error I opened a separate issue. 

Also here is the content of my `docker-compose.yml`:
```yaml
services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    ports:
      - 8000:8000
    privileged: true
    restart: unless-stopped
    user: "www-data:www-data"
    volumes:
      - ./config:/config
```
