### ISSUE TITLE
Stateful Configuration File Usage

### ISSUE THREAD

**Issue by instantdreams** [caronc/apprise-api#195]
:question: **Using a Configuration File**

I am sure I'm missing something obvious here, checking to validate my steps as I've been looking at this for far too long.

### Configuration
I first create an example configuration file with generic details:

```YAML
version: 1

urls:
  - tgram://{token_id}/{chat_id}/:
    - tag: general
  - tgram://{token_id}/{chat_id}:{topic_id}/:
    - tag: topic
```

I then set up the environment to use the correct values and right permissions:

```BASH
cd /srv/apprise
mkdir attach config plugin
cp apprise.example.yaml config/apprise.yaml
nano config/apprise.yaml
sudo chown www-data:www-data --recursive attach config plugin
sudo chmod g+rwx --recursive attach config plugin
```
As part of this process I add the correct telegram tokens, chat ids, and topics.

I then stand up the container:

```BASH
docker compose pull
docker compose up --detach
sleep 8
docker compose logs
```

Here is my compose.yaml file configuration:

```YAML
name: apprise
services:
  apprise:
    container_name: apprise
    environment:
      - TZ=America/Edmonton
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_CONFIG_LOCK=no
      - APPRISE_DEFAULT_THEME=dark
    hostname: apprise
    image: caronc/apprise:latest
    ports:
      - mode: ingress
        protocol: tcp
        published: "8000"
        target: 8000
    restart: unless-stopped
    user: www-data:www-data
    volumes:
      - bind:
          create_host_path: true
        source: /srv/apprise/attach
        target: /attach
        type: bind
      - bind:
          create_host_path: true
        source: /srv/apprise/config
        target: /config
        type: bind
      - bind:
          create_host_path: true
        source: /srv/apprise/plugin
        target: /plugin
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
        type: bind
```

### Status
The following commands all work:

```BASH
$ docker exec apprise apprise --help
Usage: apprise [OPTIONS] SERVER_URL [SERVER_URL2 [SERVER_URL3]]
...

$ docker exec apprise apprise --config /config/apprise.yaml --body "Hello there" --title "General Kenobi" --tag general

$ docker exec apprise apprise --config /config/apprise.yaml --body "Hello there" --title "General Kenobi" --tag topic
```

### The Assumption
When I access my server at http://[server-ip]:8000/ I would expect to see the configuration visible under the Configuration Manager so I can review and test the settings from the web ui.

### The Question
Do I to use the [add](https://github.com/caronc/apprise-api#persistent-stateful-storage-solution) function? If so, are there any curl examples that I could use?

**Comment by instantdreams** [comment]
I've added the `APPRISE_CONFIG_DIR` environment value to no effect.

Here is the compose config:

```YAML
name: apprise
services:
  apprise:
    container_name: apprise
    environment:
      - TZ=America/Edmonton
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_CONFIG_LOCK=no
      - APPRISE_DEFAULT_THEME=dark
      - APPRISE_CONFIG_DIR=/config
    hostname: apprise
    image: caronc/apprise:latest
    ports:
      - mode: ingress
        protocol: tcp
        published: "8000"
        target: 8000
    restart: unless-stopped
    user: www-data:www-data
    volumes:
      - bind:
          create_host_path: true
        source: /srv/apprise/attach
        target: /attach
        type: bind
      - bind:
          create_host_path: true
        source: /srv/apprise/config
        target: /config
        type: bind
      - bind:
          create_host_path: true
        source: /srv/apprise/plugin
        target: /plugin
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/timezone
        target: /etc/timezone
        type: bind
      - bind:
          create_host_path: true
        read_only: true
        source: /etc/localtime
        target: /etc/localtime
        type: bind
```

Here are the logs:

```
apprise  | 2024-06-13 08:45:16,184 INFO Set uid to user 33 succeeded
apprise  | 2024-06-13 08:45:16,188 INFO supervisord started with pid 1
apprise  | 2024-06-13 08:45:17,193 INFO spawned: 'gunicorn' with pid 7
apprise  | 2024-06-13 08:45:17,198 INFO spawned: 'nginx' with pid 8
apprise  | 2024-06-13 08:45:18,200 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
apprise  | 2024-06-13 08:45:18,200 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
apprise  | [2024-06-13 08:45:18 -0600] [7] [INFO] Starting gunicorn 22.0.0
apprise  | [2024-06-13 08:45:18 -0600] [7] [INFO] Listening at: http://0.0.0.0:8080 (7)
apprise  | [2024-06-13 08:45:18 -0600] [7] [INFO] Using worker: gevent
apprise  | [2024-06-13 08:45:18 -0600] [11] [INFO] Booting worker with pid: 11
apprise  | [2024-06-13 08:45:18 -0600] [12] [INFO] Booting worker with pid: 12
apprise  | [2024-06-13 08:45:18 -0600] [13] [INFO] Booting worker with pid: 13
apprise  | [2024-06-13 08:45:18 -0600] [14] [INFO] Booting worker with pid: 14
apprise  | [2024-06-13 08:45:18 -0600] [15] [INFO] Booting worker with pid: 15
```

Here is what I see when I access the web ui:
![image](https://github.com/caronc/apprise-api/assets/15875093/55266326-275f-49c8-96f0-74be075f684e)

When I select Configuration Manager I see this:
![image](https://github.com/caronc/apprise-api/assets/15875093/1a422f56-8c5f-4910-b9e3-fab282c185c5)

I'm wondering how the id of *key* is set when apprise-api imports the configuration file. 

I have tried to add the values from the configuration key using the API:

```BASH
$ curl --request POST --form 'config=/config/apprise.yml' --form 'format=yaml' http://192.168.1.93:8000/add/notify-telegram
No valid URL(s) defined

$ curl --request POST --data '{"config": "apprise.yml", "format":"yaml"}' --header "Content-Type: application/json" http://192.168.1.93:8000/add/notify-telegram
{"error": "No valid URL(s) defined"}
```

I'm not sure why it is asking for a URL when I specified the config parameter.

I tried the add method without a key:

```BASH
$ curl --request POST --form "config=/config/apprise.yml" --form "format=yaml" http://192.168.1.93:8000/add

<!doctype html>
<html lang="en">
<head>
  <title>Not Found</title>
</head>
<body>
  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
</body>
</html>
```

Are there any other debugging options I could turn on?
