### ISSUE TITLE
Quick docker Healthcheck question

### ISSUE THREAD

**Issue by YouveGotMeowxy** [caronc/apprise-api#243]
I'm adding a healthcheck to my compose, and this appears to work so far:

```
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "https://apprise.mydomain.com/status"]
      interval: 1m
      timeout: 3s
```

Now I'd just like to change the URL from the external FQDN to an internal one so it's not having to reach out to the net every minute. something like `http://localhost/status` but that isn't working, and I can't figure out which internal URL to use instead?
