### ISSUE TITLE
An invalid notification (type=<class 'NoneType'>) was specified.

### ISSUE THREAD

**Issue by StefanSa** [caronc/apprise-api#244]
:mega: **Notification Service(s) Impacted**
E-Mail

:lady_beetle: **Describe the bug**
i convert https://github.com/camalot/apprise-webhook webhooks from harbor registry to apprise notification.
apprise-webhook sends the notification to apprise in the correct format, at least that's what it looks like.
However, the following error message is generated:
`[ERROR] apprise: An invalid notification (type=<class 'NoneType'>) was specified.`

Any ideas?
Thanks for any help

:bulb: **Screenshots and Logs**
Notification that is sent to apprise:
```
Posting data to http://apprise:8000/notify/
{
  body: 'Docker 🐳 image  scan status  harbor.scan.completed.',
  title: '*Harbor*',
  type: 'info',
  format: 'text'
}
```

error message apprise:
```
10.0.5.187 - - [14/Mar/2025:08:27:54 +0000] "POST /notify/ HTTP/1.1" 204 0 "-" "axios/0.27.2"
2025-03-14 03:28:02,712 [DEBUG] apprise: Language set to en
2025-03-14 03:28:02,712 [ERROR] apprise: An invalid notification (type=<class 'NoneType'>) was specified.
2025-03-14 03:28:02,712 [WARNING] django: NOTIFY - 127.0.0.1 - No valid URLs provided
```

docker-compose file:
```
services:
  apprise-webhook:
    image:  ghcr.io/camalot/apprise-webhook:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      APPRISE_URL: http://apprise:8000/notify/
      TEMPLATE: harbor
      #APPRISE_KEY: docker
    volumes:
      - /mnt/nfs/webhook/hooks/harbor.njk:/app/templates/harbor.njk #custom template
    networks:
      harbor: null

  apprise:
    image: caronc/apprise
    environment:
      - LANG=en_US
      - LOG_LEVEL=DEBUG
      - APPRISE_CONFIG_URL=mailto://webmail-relay.testlocal:25?from=harbor@felten-group.com&to=test@test.com
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      harbor: null

networks:
  harbor:
    name: harbor_harbor
    external: true
```
