### ISSUE TITLE
Standalone docker image

### ISSUE THREAD

**Issue by vnghia** [caronc/apprise-api#245]
:bulb: **The Idea**

Is there any reason why we need nginx inside the docker container apart from authentication. If not could we have a docker image without nginx (and we can remove supervisord as well) and let docker do the orchestration, and traefik (in my case) handle the reverse proxy as well as authentication.

I could send a PR for this feature. Thank you very much!

:hammer: **Breaking Feature**

We could publish both images: the normal one and the one with -standalone suffix so there won't be any breaking changes.

**Comment by caronc** [comment]
[Per documentation](https://docs.gunicorn.org/en/latest/deploy.html), gunicorn is advised to run behind a nginx environment which is why it is the way it is. The nginx instance also serves the static files. 

If you run just a gunicorn instance in a docker container, everything will still work provided you use the API to create/modify your configuration directly through it (no simple helper front-end). The other nice thing with the current design is that I can use a script to ensure the correct user/group permissions are set on startup which was a problem people had issues with earlier in the development. The script allows one to disable ipv6 or ipv4 if they wish too (yet another feature request).

Anyway, That's the long winded answer to why it is the way it is. 🙂

If you did a simple container, would this just sit beside the full scale one granting one to choose?What were your thoughts here?

**Comment by davecoutts** [comment]
Hi @vnghia 

I have had success serving Apprise api via Traefik using docker image `caronc/apprise:1.2.0`.
It does result in doubling proxying first via Nginix in the container, and then Traefik externally. But it seems to work fine.

The fact it works with Traefik is perhaps not the point you are making.
But I thought I'd share my docker-compose yaml config below in case it helps.


```yaml
#------------------------------------------------------------------------------

networks:
  traefik:
    external: true

#------------------------------------------------------------------------------

services:
  apprise:
    image: caronc/apprise:1.2.0
    container_name: apprise
    hostname: apprise
    networks:
      - traefik
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - APPRISE_WORKER_COUNT=1
      - APPRISE_STATEFUL_MODE=simple
    volumes:
      - ./attach:/attach
      - ./config:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.apprise.tls=true
      - traefik.http.routers.apprise.entrypoints=websecure
      - traefik.http.routers.apprise.rule=Host(`apprise.apps.lan`)
      - traefik.http.services.apprise.loadbalancer.server.port=8000      
    restart: unless-stopped

#------------------------------------------------------------------------------

#  apprise api can be found at https://apprise.apps.lan

#------------------------------------------------------------------------------
```
